### PR TITLE
Microsoft Edge Friendly tests

### PR DESCRIPTION
**Pull request by kblok**
We made some minor changes to our tests so they run with Microsoft Edge:
 * Intervention header has the URL https://to-be-replaced.invalid/feature/5718547946799104 instead of https://www.chromestatus.com/feature/5718547946799104. We are changing the "Contains" part
 * We are removing some new lines and using Trim to compare TextAsync
 * Edge launches two pages with default arguments. We are going to check that  the pages array is not empty.

### CODE REVIEW

**Comment by Meir017** [comment]
> * Edge launches two pages with default arguments. We are going to check that the pages array is not empty.

@kblok did the puppeteer project make these changes as well?

**Comment by kblok** [comment]
@Meir017 No. Do you think I should add some comments as a reference?
Chrome by default opens with one tab, whereas Edge opens with two.

**Comment by Meir017** [comment]
I think a comment should be enough.
maybe also open a pull-request on puppeteer with this change? ;)

**Comment by kblok** [comment]
@Meir017 both are great ideas.

**Comment by kblok** [comment]
Comment added @Meir017

**Pull request merged**
