### PR TITLE
Closes issue #333 by handling paths with spaces in them.

### LINKED ISSUE #333: Chrome process launch fails when Windows user name contains 'special' characters.
My name on some Windows installations is embedded into the user directory so that it comes out as 

`C:\Users\Ryan O'Neill\AppData\....`

There are two problems here, the space and the apostrophe. I imagine other characters will cause this issue too. When launching Chrome, the process ignores all of the characters past the space and shows this error (via a popup dialogue, visible when headless is turned off);

> Failed to Create Data Directory
> Chromium cannot read or write to its data directory:
> C:\Users\Ryan

This can be rectified in Launcher.cs by amending;
`                    chromeArguments.Add($"{UserDataDirArgument}={options.UserDataDir}");
`
to
`                    chromeArguments.Add($"{UserDataDirArgument}=\"{options.UserDataDir}\"");
`

To reproduce this error, create a Windows user with a space in their name. A lot of the unit tests then fail.

I am happy to provide a pull-request, but thought I would check first.

### PR DESCRIPTION
**Pull request by RyanONeill1970**
closes #333

### CODE REVIEW

**Comment by RyanONeill1970** [comment]
I didn't add a test for downloading a full Chromium to a path with a space in it as it seemed due to the download time, but I can add it if you wish.

There are other unrelated tests which are failing on a \r and \r\n comparison in their results.

**Comment by kblok** [comment]
@RyanONeill1970 if tests are green I'm good.

**Comment by Meir017** [comment]
can we use extensions methods like https://github.com/cake-build/cake/blob/develop/src/Cake.Core/Extensions/StringExtensions.cs

**Comment by RyanONeill1970** [comment]
No problem, in the Helpers folder under StringExtensions.cs?

I had never seen an unquote/quote method before I wrote these, funny how close to the Cake code they are.

**Comment by kblok** [comment]
Yeah, go for it @RyanONeill1970

**Comment by Meir017** [comment]
make sense 👍

**Comment by RyanONeill1970** [comment]
Happy to tweak more if it's not right.

**Comment by Meir017** [comment]
can we use the same implementation that cake uses?

**Comment by RyanONeill1970** [comment]
Sure, just bring those two methods in though or the whole file?

**Comment by Meir017** [comment]
I think just those methods

**Comment by kblok** [comment]
Thank you @RyanONeill1970 for your contribution. I hope this is the first of many to come :)

**Comment by RyanONeill1970** [comment]
Thanks, I hope so too. Keep up the good work, it's a really useful tool. I may have spotted some more issues, will run tests and let you know.

**Comment by kblok** [comment]
That's great, we have great unit test coverage, but we need more real-life usage.

**Pull request merged**
