### PR TITLE
test: verify ignoreHTTPSErrors works with puppeteer.connect

### LINKED ISSUE #466: test: verify ignoreHTTPSErrors works with puppeteer.connect
https://github.com/kblok/puppeteer/pull/5/commits/0ba72df67dc68cd28ee74f0fbd4d214ed26b31f8

### PR DESCRIPTION
**Pull request by Meir017**
closes  #466

### CODE REVIEW

**Comment by kblok** [comment]
This guy is getting stuck in AppVeyor @Meir017

**Comment by Meir017** [comment]
I'm not sure which test is causing the run to hang, any ideas?

**Comment by kblok** [comment]
Maybe because we’re not closing `originalBrowser`?

**Comment by Meir017** [comment]
@kblok Done

**Pull request merged**
