### PR TITLE
#1372 fix ssl when navigate to site with cert expiring after 2038

### PR DESCRIPTION
**Pull request by pete-reay-waters**
There aren't any 'working' SSL tests in the test suite, but I have tested a built version with my app and can confirm this fixes the issue with certs expiring > 2038

### CODE REVIEW

**Comment by kblok** [comment]
Thanks!

**Comment by pete-reay-waters** [comment]
No problem, I don't have permission to merge this, please can you merge when convenient? Thanks!

**Comment by kblok** [comment]
@pete-reay-waters this is is on v2.0.1 now.

**Comment by pete-reay-waters** [comment]
@kblok thanks very much for getting it merged and into a new version!

**Pull request merged**
